### ISSUE TITLE
the jquery-autotab not working on iphone, just working on desktop web browser

### ISSUE THREAD

**Issue by sachin87** [Mathachew/jquery-autotab#45]
the jquery-autotab not working on iphone/mobile, just working on desktop web browser  i have write extra code to make it work.

**Comment by roshan-ship-it** [comment]
@Mathachew  @sachin87 : Is this issue still persist...I am using autotab.js and i came across this discussion now wondering ...this issue is still open? i haven't tested my app in iphone yet.if its not fixed then could you please suggest what is work around except @Mathachew  mentioned above..Thanks..
